[build]
  publish = "public"
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/get-data"
  status = 200

[[redirects]]
  from = "/api/save-data"
  to = "/.netlify/functions/save-data"
  status = 200

[[redirects]]
  from = "/api/check-password"
  to = "/.netlify/functions/check-password"
  status = 200

[[redirects]]
  from = "/api/diagnostico"
  to = "/.netlify/functions/diagnostico"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[functions]
  node_bundler = "esbuild"
